### ISSUE TITLE
[DATA REQUEST] Bureau of Meteorology Atmospheric Regional Projections for Australia (BARPA)

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-nri-intake-catalog#197]
# Description of the data product

BARPA Projections contains a moderate-resolution and a kilometre-scale regional climate projections over Australia and surrounding regions. The current collections are developed based on CMIP6 global climate projections. It consists of an ensemble of historical and future climate model fields. It can be used for climate research, impact modelling, developing climatology products, and future likelihood products, driving downstream impact modelling (e.g., hydrological, coastal, and fire), for case studies and stress testing of environments, infrastructure and assets under different future scenarios.

# Location of the data product on Gadi

NCI intake catalog available in
/g/data/py18

# Checklist

Add a "x" between the brackets to all that apply
- [X] This data product is stable (unlikely to change substantially or move)
- [X] This data product is of use to the broader community
- [X] This data product is documented: [link](https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f3062_7036_5200_2977)
- [X] This data product is licensed under Creative Commons Attribution 4.0 International
- [X] Those who want to access this data can be added to the project that houses it

**Comment by marc-white** [comment]
Have requested membership of this project to investigate.

**Comment by marc-white** [comment]
Existing CMIP6 Intake-ESM catalog, so no new builder should be required. However, there isn't a metadata.yaml for this experiment (https://access-nri-intake-catalog.readthedocs.io/en/latest/management/building.html#metadata-yaml-files).

@rbeucher who would be the best person to add one for this experiment?

**Comment by rbeucher** [comment]
I am not sure how @dougiesquire did for the fs38, oi10 etc collection. It should be similar.

**Comment by marc-white** [comment]
It's interesting, the config files inside `access-nri-intake-catalog` reference `metadata.yaml` for those experiments that don't exist. I'm trying to work out if they're just dummies to keep the system happy, or if they did once exist but now aren't needed for some reason.

**Comment by dougiesquire** [comment]
They should exist. If they don't it sounds like they could've been accidentally deleted... I can take a better look later today

**Comment by marc-white** [comment]
@dougiesquire the CMIP5 and CMIP6 experiments all refer to yamls stored in `/g/data/tm70/intake`, which doesn't exist. A search shows that there are a few `metadata.yaml` hiding within `/g/data/tm70`, but nothing that `access-nri-intake-catalog` appears to reference.

**Comment by dougiesquire** [comment]
Hmm, that folder used to exist. I guess it's been deleted (possibly by me??).

It should be possible to recreate the contents of the `metadata.yaml` from the latest (or prior) version of the catalog. E.g. something like:

```python
catalog["cmip6_fs38"].metadata
```

**Comment by rbeucher** [comment]
NCI has changed the way they deploy intake catalogs. They are now in each collection. That might be what is happening here.

**Comment by marc-white** [comment]
I'll shift the missing YAMLs into a new issue. Meanwhile, I think there's enough information in the existing `catalog.json` to be able to construct a sensible `metadata.yaml` myself. Should I put it in a 'master' folder under `tm70`, or drop it in the same place as the catalog? I presume the latter, but I'm nervous about touching data archives without explicit permission.

**Comment by rbeucher** [comment]
I would keep things with the catalog

**Comment by marc-white** [comment]
Please confirm this YAML is acceptable for this dataset:

```yaml
name: cmip6_py18
experiment_uuid: 0cc28d8c-7ba5-11ef-a9ea-000007d3fe80
description: Bureau of Meteorology Atmospheric Regional Projections for Australia (BARPA)
long_description: >-
  BARPA Projections contains a moderate-resolution and a kilometre-scale regional climate projections over 
  Australia and surrounding regions. The current collections are developed based on CMIP6 global climate projections. 
  It consists of an ensemble of historical and future climate model fields. 
  It can be used for climate research, impact modelling, developing climatology products, and future likelihood products, 
  driving downstream impact modelling (e.g., hydrological, coastal, and fire), for case studies and stress testing 
  of environments, infrastructure and assets under different future scenarios.
model:
- CMIP6
frequency:
- 
variable:
- evspsblpot
- vasmax
- zmla
- ta200m
- CAPE
- ta150m
- wsgsmax
- CIN
- va200m
- pr
- hfls
- rsut
- clwvi
- ta250m
- sfcWind
- cll
- clt
- ua300
- ta70
- ua1500m
- tsl
- va30
- ua400
- wa850
- mrros
- ua250
- hus10
- hus70
- rlut
- wa500
- va250m
- rlutcs
- wa700
- prw
- clivi
- ua50
- va100
- va700
- ua200m
- hus100
- rsdsdir
- vas
- snm
- hurs
- zg150
- psl
- va200
- wa600
- ps
- ua100
- va100m
- zg50
- rsdscs
- prc
- mrfso
- ua250m
- ua1000
- wa150
- ta400
- wa300
- wa50
- va500
- hus150
- va150
- sfcWindmax
- tasmin
- zg70
- wa250
- ta500
- mrsol
- wa70
- zg700
- ua925
- zg250
- ua10
- wa30
- zg400
- ua600
- va250
- ta950
- ua30
- va300
- wa400
- ua200
- ta150
- hus250
- ua70
- tauv
- zg30
- hfss
- vasmean
- rldscs
- ta50m
- mrfsos
- uas
- uasmean
- rsds
- clh
- tasmean
- mrsos
- rluscs
- uasmax
- ta1500m
- rsuscs
- ta20
- va50
- ua150m
- ta600
- prsn
- ta30
- zg300
- hus500
- mrfsol
- ta300
- zg200
- zg600
- hus1000
- ta10
- ta700
- ua500
- zg20
- rsutcs
- tauu
- ua100m
- va1500m
- rlds
- ta1000
- wa10
- hus400
- ta850
- ua700
- ta100
- zg925
- hus50
- rsdt
- zg100
- sic
- hus600
- hus700
- ta200
- ta50
- va10
- ts
- ta100m
- ua850
- hus20
- zg850
- hus850
- wa1000
- va1000
- snw
- rlus
- rsus
- va150m
- prhmax
- hus925
- tasmax
- va50m
- va925
- ua50m
- hus200
- ta925
- ua150
- snd
- ta250
- mrso
- hus30
- mrro
- wa20
- va70
- va400
- zg500
- z0
- omega500
- sund
- ua20
- va20
- clm
- va600
- wa925
- wa100
- zg10
- huss
- zg1000
- wa200
- va850
- tas
- hus300
- hus950
- sftlf
- evspsbl
- orog
nominal_resolution:
- 
version: 
contact: NCI
email: help@nci.org.au
reference:
license:
url: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f3062_7036_5200_2977
parent_experiment:
related_experiments:
-
notes: 
keywords:
- cmip
```

**Comment by rbeucher** [comment]
What are the restrictions on the source names. This is not CMIP6 but BARPA. I think we need to decide on meaningful short names.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by marc-white** [comment]
I don't think there are any restrictions on the model name(s) per se, it's simply a set of strings that the user can search against. That being said, is BARPA it's own "model", or is it a custom collection of CMIP6 outputs?

**Comment by rbeucher** [comment]
BARPA is the model but the collection name is Bureau of Meteorology... So bom_py18 is better here. It follows the CMIP format but it is not CMIP. It's regional models.

**Comment by rbeucher** [comment]
```
name: barpa_py18
keywords:
- barpa
- bom
- cmip
```

Otherwise looks good

**Comment by marc-white** [comment]
Updated metadata:

```yaml
name: barpa_py18
experiment_uuid: 0cc28d8c-7ba5-11ef-a9ea-000007d3fe80
description: Bureau of Meteorology Atmospheric Regional Projections for Australia (BARPA)
long_description: >-
  BARPA Projections contains a moderate-resolution and a kilometre-scale regional climate projections over 
  Australia and surrounding regions. The current collections are developed based on CMIP6 global climate projections. 
  It consists of an ensemble of historical and future climate model fields. 
  It can be used for climate research, impact modelling, developing climatology products, and future likelihood products, 
  driving downstream impact modelling (e.g., hydrological, coastal, and fire), for case studies and stress testing 
  of environments, infrastructure and assets under different future scenarios.
model:
- BARPA
frequency:
- 
variable:
- evspsblpot
- vasmax
- zmla
- ta200m
- CAPE
- ta150m
- wsgsmax
- CIN
- va200m
- pr
- hfls
- rsut
- clwvi
- ta250m
- sfcWind
- cll
- clt
- ua300
- ta70
- ua1500m
- tsl
- va30
- ua400
- wa850
- mrros
- ua250
- hus10
- hus70
- rlut
- wa500
- va250m
- rlutcs
- wa700
- prw
- clivi
- ua50
- va100
- va700
- ua200m
- hus100
- rsdsdir
- vas
- snm
- hurs
- zg150
- psl
- va200
- wa600
- ps
- ua100
- va100m
- zg50
- rsdscs
- prc
- mrfso
- ua250m
- ua1000
- wa150
- ta400
- wa300
- wa50
- va500
- hus150
- va150
- sfcWindmax
- tasmin
- zg70
- wa250
- ta500
- mrsol
- wa70
- zg700
- ua925
- zg250
- ua10
- wa30
- zg400
- ua600
- va250
- ta950
- ua30
- va300
- wa400
- ua200
- ta150
- hus250
- ua70
- tauv
- zg30
- hfss
- vasmean
- rldscs
- ta50m
- mrfsos
- uas
- uasmean
- rsds
- clh
- tasmean
- mrsos
- rluscs
- uasmax
- ta1500m
- rsuscs
- ta20
- va50
- ua150m
- ta600
- prsn
- ta30
- zg300
- hus500
- mrfsol
- ta300
- zg200
- zg600
- hus1000
- ta10
- ta700
- ua500
- zg20
- rsutcs
- tauu
- ua100m
- va1500m
- rlds
- ta1000
- wa10
- hus400
- ta850
- ua700
- ta100
- zg925
- hus50
- rsdt
- zg100
- sic
- hus600
- hus700
- ta200
- ta50
- va10
- ts
- ta100m
- ua850
- hus20
- zg850
- hus850
- wa1000
- va1000
- snw
- rlus
- rsus
- va150m
- prhmax
- hus925
- tasmax
- va50m
- va925
- ua50m
- hus200
- ta925
- ua150
- snd
- ta250
- mrso
- hus30
- mrro
- wa20
- va70
- va400
- zg500
- z0
- omega500
- sund
- ua20
- va20
- clm
- va600
- wa925
- wa100
- zg10
- huss
- zg1000
- wa200
- va850
- tas
- hus300
- hus950
- sftlf
- evspsbl
- orog
nominal_resolution:
- 
version: 
contact: NCI
email: help@nci.org.au
reference:
license:
url: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f3062_7036_5200_2977
parent_experiment:
related_experiments:
-
notes: 
keywords:
- barpa
- bom
- cmip
```

@rbeucher are you able to place this as `metadata.yaml` somewhere within `py18`, or should we use whatever location we come up with in #200 for storing it? I think the deepest I can write inside `py18` is down to the level of `/g/data/py18/catalog/v2`.
