### ISSUE TITLE
[DATA REQUEST] NARCliM2.0 Australasia (AUS-18) dynamically downscaled from ACCESS-ESM1-5 historical using WRF412R3

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-nri-intake-catalog#198]
# Description of the data product

NARCliM2.0 climate projections dynamically downscaled from ACCESS-ESM1-5 r6i1p1f1 historical model using the WRF regional model version NARClIM2-0-WRF412R3. Domain covers a region encompassing CORDEX Australasia (AUS-18) at approximately 18km resolution in rotated grid format.
The dataset includes 1-hour, 3-hour, daily and monthly data for variables such as temperature, humidity, wind, radiation and precipitation parameters. Data are provided at 1-hour steps for surface-level variables, other data at atmospheric pressure levels or subsurface processes is provided as 3-hour, daily and monthly data. Dataset includes all of CORDEX Core variables, most of the CORDEX Tier 1 and just over half of CORDEX Tier 2 variables.

# Location of the data product on Gadi

Catalog available in:
/g/data/zz63

# Checklist

Add a "x" between the brackets to all that apply
- [X] This data product is stable (unlikely to change substantially or move)
- [X] This data product is of use to the broader community
- [X] This data product is documented: [link](https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f7334_2646_2487_9846)
- [X] This data product is licensed under Creative Commons Attribution 4.0 International
- [X] Those who want to access this data can be added to the project that houses it

**Comment by marc-white** [comment]
Have requested membership of this project to investigate.

**Comment by marc-white** [comment]
I have completed a YAML for this dataset. Please confirm it is suitable (in particular, please confirm the models list is correct and complete; I was unsure if this was CMIP6 only, or should also be classed as ACCESS-ESM1.5):

```yaml
name: cmip6_zz63
experiment_uuid: c601ae44-7b9c-11ef-be76-000007d3fe80
description: CNARCliM2.0 Australasia (AUS-18) dynamically downscaled from ACCESS-ESM1-5 historical using WRF412R3
long_description: >-
  NARCliM2.0 climate projections dynamically downscaled from ACCESS-ESM1-5 r6i1p1f1 historical model using the 
  WRF regional model version NARClIM2-0-WRF412R3. 
  Domain covers a region encompassing CORDEX Australasia (AUS-18) at approximately 18km resolution in rotated grid format.
  The dataset includes 1-hour, 3-hour, daily and monthly data for variables such as temperature, humidity, wind,
  radiation and precipitation parameters. 
  Data are provided at 1-hour steps for surface-level variables, other data at atmospheric pressure levels or 
  subsurface processes is provided as 3-hour, daily and monthly data. Dataset includes all of CORDEX Core variables, 
  most of the CORDEX Tier 1 and just over half of CORDEX Tier 2 variables.
model:
- CMIP6
frequency:
- 1hr
- day
- mon
- 6hr
- fx
variable:
- prsn
- hfss
- rlus
- uas
- evspsbl
- prc
- rsdscs
- hus850
- wa300
- ta850
- sfcWind
- tasmin
- rsut
- hus300
- ts
- rsdsdir
- wa750
- hus500
- ta70
- CIN
- hus200
- ta500
- wa100
- ps
- prhmax
- ta400
- rsuscs
- ua250m
- zg200
- hus400
- snw
- ua1000
- mrfsos
- ta100
- lai
- zg1000
- zg925
- wa1000
- tasmax
- hus700
- rsus
- va750
- rlds
- hus250
- clwvi
- ta300m
- wa250
- wa925
- prw
- va600
- va925
- ta300
- rsds
- rlutcs
- mrsos
- ua600
- vas
- ua925
- rldscs
- va500
- hus300m
- va1000
- tsl
- ua300m
- pr
- hus70
- ua50m
- va200m
- va250
- va250m
- siconca
- CINmax
- snm
- zmla
- rluscs
- ua150m
- ua100
- va50m
- zg250
- ta700
- zg700
- hurs
- hus150
- tauu
- ua150
- ua100m
- zg70
- wa500
- psl
- zg750
- hus50m
- rsutcs
- ua250
- wa150
- zg100
- ua70
- ta750
- hus1000
- va300m
- ua400
- va100m
- ua850
- va100
- ua200
- zg150
- hus925
- zg300
- clivi
- ta1000
- ta600
- rsdt
- ua200m
- tauv
- hfls
- evspsblpot
- tas
- huss
- wa850
- wa400
- ua300
- va850
- ua500
- va400
- hus100
- ta250
- wa600
- zg850
- mrfso
- zg400
- CAPEmax
- ua700
- wa700
- zg600
- ua750
- ta200
- va150m
- CAPE
- wa200
- snc
- ta50m
- ta925
- clt
- hus600
- va150
- va200
- vegFrac
- va700
- rlut
- sfcWindmax
- va300
- ta150
- hus750
- zg500
- wa70
- snd
- mrso
- va70
- orog
- sftlf
- areacella
nominal_resolution:
- NARCliM2-0-WRF412R3
- NARCliM2-0-WRF412R5
version: 
contact: NCI
email: help@nci.org.au
reference:
license:
url: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f7334_2646_2487_9846
parent_experiment:
related_experiments:
-
notes: 
keywords:
- cmip
```
