### ISSUE TITLE
[DATA REQUEST] 20km regional projections for CORDEX-CMIP6 from the Queensland Future Climate Science Program

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-nri-intake-catalog#199]
# Description of the data product

This dataset includes projections at 20km, formatted to meet the CORDEX-CMIP6 data standards. The 20km projections were derived from the 10km projections.

# Location of the data product on Gadi

Catalog available in /g/data/ig45
# Checklist

Add a "x" between the brackets to all that apply
- [X] This data product is stable (unlikely to change substantially or move)
- [X] This data product is of use to the broader community
- [X] This data product is documented: [link](https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f7465_8388_5100_7022)
- [X] This data product is licensed under Creative Commons Attribution 4.0 International
- [X] Those who want to access this data can be added to the project that houses it

**Comment by marc-white** [comment]
Have requested membership of this project to investigate.

**Comment by marc-white** [comment]
Please confirm this YAML is suitable for the dataset:

```yaml
name: cmip6_ig45
experiment_uuid: c7021d1e-7ba2-11ef-beb5-000007d3fe80
description: 20km regional projections for CORDEX-CMIP6 from the Queensland Future Climate Science Program
long_description: >-
  This dataset includes projections at 20km, formatted to meet the CORDEX-CMIP6 data standards. 
  The 20km projections were derived from the 10km projections.
model:
- CMIP6
frequency:
- 
variable:
- 
nominal_resolution:
- 
version: 
contact: NCI
email: help@nci.org.au
reference:
license:
url: https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/f7465_8388_5100_7022
parent_experiment:
related_experiments:
-
notes: 
keywords:
- cmip
```
