### ISSUE TITLE
[BUG] Missing ERAI `metadata.yaml`

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#224]
# Describe the bug

In `config/era.yaml`, we have

```yaml
builder: null

translator: EraiTranslator

sources:

  - metadata_yaml: /g/data/tm70/intake/metadata/erai/metadata.yaml
    path:
      - /g/data/hh5/public/apps/nci-intake-catalogue/erai/catalogue.json
```

However, the metadata_yaml file (` /g/data/tm70/intake/metadata/erai/metadata.yaml`) doesn't exist, nor can it be found in `/g/data/xp65/admin/intake/`:
```bash
[ct1163@gadi-login-06 metadata]$ cd /g/data/xp65/admin/intake/metadata/
[ct1163@gadi-login-06 metadata]$ tree .
.
├── cmip5_al33
│   └── metadata.yaml
├── cmip5_rr3
│   └── metadata.yaml
├── cmip6_fs38
│   └── metadata.yaml
├── cmip6_ig45
│   └── metadata.yaml
├── cmip6_oi10
│   └── metadata.yaml
├── cordex_ig45
│   └── metadata.yaml
└── rcm_ccam_hq89
    └── metadata.yaml

7 directories, 7 files
```

I'm assuming this is related to #200.
# To Reproduce

On Gadi, run 
```bash
cat /g/data/tm70/intake/metadata/erai/metadata.yaml
```
# Additional context

I noticed this when trying to figure out what to put in the model field for the metadata.yaml for #214.
