### ISSUE TITLE
Catalog polling to infer & exclude broken datastores

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#308]
# Is your feature request related to a problem? Please describe.

This package indexes & includes a number of datastores in the catalog via way of Translators - eg. those in #211 #199, etc, etc.

These datastores are typically owned by other users/groups on Gadi, and so are liable to break if their owners make alterations to the relevant catalog files (examples of where these are likely to be located can be found in the `config` section of this package).

Although these breakages are not strictly speaking a breakage of the ACCESS-NRI Intake Catalog, they will appear to users as such, as attempting to open a broken datastore will trigger an error. To handle this, we should implement some sort of procedure to ensure that all datastores included in the live catalog are functioning.

# Describe the feature you'd like

There should be some functionality that allows us to continually poll the catalog at regular intervals (eg. midnight every night) to ensure that all datastores are correctly functioning.

The tests introduced by #290 (`tests/e2e/test_datasets_representative`) attempt to build all datastores from translators, forcing the assumption that the datastores can still be opened & translated using the same translators that were valid when the datastores were added into the catalog. This, in essence, forms a regression test for the datastore validity, and the functionality therein could be adapted & extended to ensure datastore integrity.

Additional considerations:
- Some translators are applied to multiple datastores: eg. `cmip6.yaml`:
```yaml
builder: null

translator: Cmip6Translator

sources:

  - metadata_yaml: /g/data/xp65/admin/access-nri-intake-catalog/config/metadata_sources/cmip6-fs38/metadata.yaml
    path:
      - /g/data/fs38/catalog/v2/esm/catalog.json
    
  - metadata_yaml: /g/data/xp65/admin/access-nri-intake-catalog/config/metadata_sources/cmip6-oi10/metadata.yaml
    path:
      - /g/data/oi10/catalog/v2/esm/catalog.json

```
If, for example, the `cmip6-fs38` datastore were broken, care would need to be taken to ensure that the `cmip6-oi10` datastore was not also excluded (in this instance erroneously).
- There may be additional considerations around missing files - it is easy & computationally cheap to ensure that datastores are not broken. It is potentially substantially harder & more computationally expensive to ensure that no files within a datastore have been altered or moved in a way that breaks the catalog - perhaps a binhash solution like suggested in #272 would be an approach that would address these concerns.
- We would need to consider how to address breakages - would we automatically trigger a catalog rebuild, excluding missing artifacts? How would we warn catalog users of missing data due to newly broken datastores? 

# Additional context

- We may also want to apply a similar procedure towards datastores created using builders, as well as translators. This would require some additional thought regarding implementation.
