### ISSUE TITLE
Auto-copy `metadata.yaml`s to gadi

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#388]
# Is your feature request related to a problem? Please describe.

In eg. `egfs-ref.yaml` (see #381):
```yaml
builder: null

translator: EsgfTranslator

sources:

  - metadata_yaml: /g/data/xp65/admin/intake/metadata/esgf-ref-qv56/metadata.yaml
    path:
      - /g/data/qv56/catalog/v2/esm/catalog.json
```

This metadata.yaml file needs to be manually copied into the right spot on Gadi when the PR is merged.

# Describe the feature you'd like

This could probably be achieved via a hook in the CI.
